import './globals.css'
import Navbar from './components/navbar/navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App', // 'Library Portal - IIITB '
  description: 'Generated by create next app', // 'Admin Library portal of IIITB 
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar> </Navbar>
        {children}
        {/* <footer> </footer> */}
        <script src="https://kit.fontawesome.com/dbc8b356b9.js" crossOrigin="anonymous"></script>
      </body>
    </html>
  )
}
